### ISSUE TITLE
Need dataBase backup

### ISSUE THREAD

**Issue by mobinaghashahi** [T0k0saba/food-order-site#1]
Hi my friend.
i want use your code and I need ur dataBase.
can u add ur dataBase to your code?
I do this work for practice git.
tnks.

**Comment by T0k0saba** [comment]
Hello!
I am making this practice site within this course [https://www.youtube.com/watch?v=ZBgTzx46B8s](url) . 
You have to follow the instructions in the videos and you can create your own database locally. :)
It is easy

**Comment by mobinaghashahi** [comment]
ok. I added it.
